name: BenSlater
favicon: null
layout_spectrum: 0
typography_spectrum: 0.06839
title: Ben Slater
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#100f14'
    - '#e7d6c4'
    - '#a49987'
    - '#746454'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
