name: BenSlater
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8103
title: Ben Slater
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#323230'
    - '#b5b6b6'
    - '#25c437'
    - '#9c2843'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
