name: BenSlater
favicon: null
layout_spectrum: 0.028606767766177654
typography_spectrum: 0.716843620641157
title: Ben Slater
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#24212c'
    - '#6d6161'
    - '#46404a'
    - '#978276'
  brandStrength: 0.75
  lightness: 0.9324937884230167
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
