name: BenSlater
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16779
title: Ben Slater
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#24212c'
    - '#6d6161'
    - '#46404a'
    - '#978276'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
